name: povoamento
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Povoamento'     
        required: false
        default: ''

jobs:
  povoar_site:
    runs-on: macOS-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: docker://pandoc/core:2.9
      
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Instala pacotes
        run: |   
          install.packages(c("rmarkdown","purrr","dplyr","glue","forcats","grid","ggplot2","tidyr","ggbump","ggiraph","stringr","ggpath","ragg","scales","import"))
        shell: Rscript {0}
       
      - name: Roda o script de gatilho do gerador
        run: |   
          source("R/gatilho.R")
        shell: Rscript {0}
        
      - name: Efetua commit dos resultados
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add cidades_docs/*
          git commit -m "Latest data: `date +'%Y-%m-%d %H:%M:%S'`" || exit 0
          git push
