name: povoamento
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Povoamento'     
        required: false

jobs:
  povoar_site:
    runs-on: macOS-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
                
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
      
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Instala pacotes
        run: |   
          install.packages(c("rmarkdown","purrr","dplyr","glue","forcats","grid","ggplot2","tidyr","ggbump","ggiraph","stringr","ggpath","ragg","scales","import","ggtext","systemfonts","quarto"))
        shell: Rscript {0}

      - name: Roda o script de gatilho do gerador
        run: |   
          source("R/gatilho.R")
        shell: Rscript {0}
        
      - name: Efetua commit dos resultados
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add --all
          git commit -m "Latest run: `date +'%Y-%m-%d %H:%M:%S'`" || exit 0
          git push
